apiVersion: apps/v1
kind: Deployment
metadata:
  name: agri-python-devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agri-fastapi
  template:
    metadata:
      labels:
        app: agri-fastapi
    spec:
      containers:
        - name: agri-python-devops
          image: abuoken/agri-python-devops:latest
          ports:
            - containerPort: 8000
