apiVersion: v1
kind: Service
metadata:
  name: agri-fastapi
  labels:
    app: agri-fastapi
spec:
  selector:
    app: agri-fastapi
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
