apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agri-python-devops
spec:
  project: default
  source:
    repoURL: https://github.com/Abouken77/agri-python-devops.git
    targetRevision: main
    path: helm/agri-fastapi
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
